### ISSUE TITLE
[Android & iOS] Can I use this package to share a mp3 file from local?

### ISSUE THREAD

**Issue by hanpanpan200** [EstebanFuentealba/react-native-share#104]
I want to share a mp3 file in the App. 

```
if (localFilePath) {
      const options = { url: localFilePath }
      Share.open(options).catch(e => console.log(e))
}
```
But it will shows an error.

I notice that I must use a base64 file url, does that mean:

```
RNFetchBlob.fs.readFile(filePath, 'base64').then(data => {
    console.log('data>>>', data)
    const options = { url: data }
    Share.open(options).catch(e => console.log(e))
})
``` 

But then I still got an error:
`Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference`

`ShareFile.java: 64  isBase64File`
`ShareFile.jave:61  ifFile`

Can this package be used to share the mp3 file? if so, how?  @EstebanFuentealba

**Comment by ataillefer** [comment]
Hi,

When you say "But it will shows an error.", can you provide the stack trace?

You are getting an error when using base64 probably because the `url` property should match the following pattern:
```
"data:image/png;base64,<base64_data>"
```
as for the `TWITTER_ICON` in https://github.com/EstebanFuentealba/react-native-share/blob/master/README.md#usage

**Comment by hanpanpan200** [comment]
Hi @ataillefer Thanks for your reply! 

I added the format for my url data as below:

```
if (filePath) {
      console.log('filePath', filePath) 
     // filePath /data/user/0/com.demo/files/Gary Gao12-08-2016 13-53-52.mp3
      RNFetchBlob.fs.readFile(filePath, 'base64').then(data => {
        const base64Url = `data:audio/mp3;base64,${data}`
        console.log('base64Audio>>>', base64Url)
        //  base64Audio>>>    data:audio/mp3;base64,/+NIxAAAAAA
        const options = { url:  base64Url}
        Share.open(options).catch(e => console.log(e))
      })
    }
```

I didn't get error this time, but the file I shared it's not correct. 

I shared a file named:  `1486454572302.null`, instead of `Gary Gao12-08-2016 13-53-52.mp3`

Are there some additional options that I need to configure?

**Comment by hanpanpan200** [comment]
Hi @ataillefer 

If I'd like to make the file extension to be `mp3`, shall I pass the `type` params to specify the `File mime type (optional)`? 

Could you please tell me what value should `type` be? I tried `mp3` but it didn't work. 

I can not find the available options for `type` in the document.

**Comment by ataillefer** [comment]
Hi,

About the file type, it should work by passing the full MIME type: `audio/mp3` or `audio/mpeg` as the `type` option.

About the file name, unfortunately if you look at the [code used for a base64 encoded file](https://github.com/EstebanFuentealba/react-native-share/blob/master/android/src/main/java/cl/json/ShareFile.java#L119) you'll see that it uses a timestamp, thus the `1486454572302` name.

I think you should use a local file instead of base 64 if you want to share a file.

**Comment by hanpanpan200** [comment]
Hi @ataillefer 
How can I share a local file instead of a base 64 file?

I tired:

```
const options = { url: filePath}
Share.open(options).catch(e => console.log(e))
```
It will show error: `Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference`.

Then if I tried:

```
RNFetchBlob.fs.readFile(filePath).then(data => {
    const options = { url:  data}
    Share.open(options).catch(e => console.log(e))
})
```
The `open` method will throw an error, the Share ActionSheet can not popup.

How can I share the local file directly with this package?

**Comment by ataillefer** [comment]
Have you tried:
```
options = {
  url: `file://${filePath}`,
  type: 'audio/mp3',
}
```
?

**Comment by hanpanpan200** [comment]
Hi @ataillefer 
Thanks for your help! it works!

This library does support the local file share!

But the Readme file seems to make users think that only when we encode the files to be base 64, can we share it.

I'm very confusing, that's why I tired to share a file that encoded with base 64.

Now I know I can share a file directly with the corresponding url format, so I made a [pull request](https://github.com/EstebanFuentealba/react-native-share/pull/105) to update the readme file.

I think it can be useful if the readme can provide the formats for url, which can make it easy for use.

**Comment by zachgibson** [comment]
@ataillefer @hanpanpan200 What does 'filePath' look like in 

``options = {
  url: `file://${filePath}`,
  type: 'audio/mp3',
}``?

I'm trying to share a local mp3 file but not having any luck. 😒

**Comment by ataillefer** [comment]
It's a path to Android's internal or external storage.
Typically, using [react-native-fetch-blob](https://github.com/wkh237/react-native-fetch-blob), it coulde be:
- /data/user/0/my.app.package/files/myFile.pdf using `RNFetchBlob.fs.dirs.DocumentDir`
- /data/user/0/my.app.package/cache/myFile.pdf using `RNFetchBlob.fs.dirs.CacheDir`
- /storage/emulated/0/DCIM/myFile.pdf using `RNFetchBlob.fs.dirs.DCIMDir`
- /storage/emulated/0/Download/myFile.pdf using `RNFetchBlob.fs.dirs.DownloadDir`

**Comment by hanpanpan200** [comment]
Hi @zachgibson , when you share the file, what's the file location? 
and @ataillefer I'm afraid that sharing file from Android internal storage path can not work in `react-native-share@1.0.19`. 
Because sharing need to access your App's data, and the data in Android internal storage can't be retrieved from other Apps.

Please check if your file location is valid.

I have some [demo code](https://github.com/hanpanpan200/RN-android-download-share) for sharing file from Android. In that demo, I 
- Download file
- Save the file to Android External Storage
- Share file from that Android External Storage

Hope it can be helpful.

**Comment by gasipari** [comment]
Hi @hanpanpan200 @ataillefer @zachgibson 

For Android, [react-native-fs](https://github.com/itinance/react-native-fs)'s `DocumentDirectoryPath` actually maps to the app's files directory. I think there is no need to download a remote file, save/share the file to/from Android External Storage.

  ```
share = () => {
    const RNFS = require('react-native-fs')
    const filePath = `${RNFS.DocumentDirectoryPath}/abc.mp3`
    Share.open({
      url: `file://${filePath}`
    }).catch(err => {
      console.log(JSON.stringify(err))
    })
  }
```

**Comment by Shanie1331** [comment]
@hanpanpan200 @ataillefer @zachgibson @gasipari @heracek any help will be appreciated
Android 8.1.0, api 27...

build.gradle(module app)


```
android {
    compileSdkVersion 27
    buildToolsVersion '28.0.3'
}
build.gradle (project: xxx)

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}

```

Android.manifest...

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

<application
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:allowBackup="false"
  android:theme="@style/AppTheme">
  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:windowSoftInputMode="adjustPan">
      <intent-filter>
          <action android:name="android.intent.action.SEND" />
          <category android:name="android.intent.category.DEFAULT" />
          <data android:mimeType="text/plain" />
          <data android:mimeType="image/*" />
      </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
    </intent-filter>
  </activity>
  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    <provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.fileprovider"
        android:grantUriPermissions="true"
        android:exported="false">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/file_paths"/>
    </provider>
</application>

```

I am taking permissions from android like this : ----->

```
if(Platform.OS ==='android'){try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
        {
          title: 'Cool Photo App Camera Permission',
          message:
            'Cool Photo App needs access to your camera ' +
            'so you can take awesome pictures.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can READ camera');
      } else {
        console.log('Camera permission denied');
      }
    } catch (err) {
      console.warn(err);
    }
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
        {
          title: 'Cool Photo App Camera Permission',
          message:
            'Cool Photo App needs access to your camera ' +
            'so you can take awesome pictures.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can WRITE camera');
      } else {
        console.log('Camera permission denied');
      }
    } catch (err) {
      console.warn(err);
    }}
```

this is what I am doing ------>

 ```
let base64Str = res;
            const fs = RNFetchBlob.fs
            const dirs = RNFetchBlob.fs.dirs;
            let imageLocation = dirs.DownloadDir +'/'+'reactNew.png';
            fs.writeFile(imageLocation, base64Str, 'base64');
            console.log(imageLocation)
            // RNFetchBlob.fs.scanFile([ { path : imageLocation } ])
            RNFetchBlob.fs.readFile(imageLocation, 'base64')
              .then((res) => {
                const URL = "data:image/png;base64,"+res;
                let shareOptions = {
                  // title: "React Native Share Example",
                  // message: "Check out this photo!",
                  url: URL,
                  // url: res,
                  type: 'image/png',
                  // subject: "Check out this photo!"
                }
                Share.open(shareOptions)
                  .then((result) => console.log('result:', result))
                  .catch(err => console.log('err', err))
                  console.log("scan file success")
              })
              .catch((err) => {
                console.log("scan file error")
              })
```
Response in debugger is :

> /storage/emulated/0/Download/reactNew.png ------> console.log(imageLocation)
> 
> scan file success ------> console.log("scan file success")
> 
> err {error: "Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"} ---------> .catch(err => console.log('err', err))

**Comment by mikehardy** [comment]
I only ever get these:

> err {error: "Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"} ---------> .catch(err => console.log('err', err))

...when I'm not naming the fileprovider correctly as I call it. You created a FileProvider in your AndroidManifest.xml but somehow you are not actually calling it up correctly as you try to access the files.

**Comment by stepupithubapp** [comment]
i can't share mp3 from my player in react native
