### ISSUE TITLE
Change language buttons 

### ISSUE THREAD

**Issue by vegmorse** [EstebanFuentealba/react-native-share#107]
Is it possible to change the language of the buttons (Cancel, more, ....) to other languages in Share.open(shareOptions)?

Thank you very much

**Comment by dykra** [comment]
Have you managed to achieve this? :)

**Comment by jgcmarins** [comment]
yes, it's possible to pass any React.Node to Button: https://github.com/react-native-community/react-native-share/blob/199b8dfaf1/components/Button.js#L39

**Comment by cmeiller** [comment]
Hi @jgcmarins, how to use the current language mobile to replace the default share texts (like Copy, Cancel, Add to Reading List...)?
