### ISSUE TITLE
Hot to get isCancelled from share?

### ISSUE THREAD

**Issue by lucianomlima** [EstebanFuentealba/react-native-share#108]
With use react-native-fbsdk when usar cancel share, in promise result return isCancelled property with true.
But in react-native-share, always return message = 'OK'.
How to know if user cancel share?

**Comment by Andruschenko** [comment]
It's not implemented for `Android` yet, but is available for `iOS`. See https://github.com/EstebanFuentealba/react-native-share/blob/master/index.js#L45

**Comment by lucianomlima** [comment]
@Andruschenko thanks, for iOS works. For android I realized that react-native-fbsdk do not return the result.

**Comment by Andruschenko** [comment]
Also the share implementation of the core RN doesn't support it on Android unfortunately: https://facebook.github.io/react-native/docs/share.html
