### ISSUE TITLE
Permission denied for the attachment

### ISSUE THREAD

**Issue by RUIFERNANDE5** [EstebanFuentealba/react-native-share#124]
Hey and thank you for your amazing work.
Basically I am trying to send an attachment through email but I am getting a `Permission deined for the attachment error` on Android.

On iOS the path just gets written after message body..

The file Im trying to send is a vcf file (VCard), the url Im trying to send looks like this:
`file:///data/user/0/com.appName/files/Teste-ABC.vc`

my shareOptions object:

```
shareOptions: {
    title: 'Share VCard',
    url: `file://${file}`,
    type: 'vcf',
    message: 'VCard Test'
},
```

And, Im using the shareSingle option like this:

```
Share.shareSingle(Object.assign(shareOptions, {
    "social": "email"
}));
```

**Comment by RUIFERNANDE5** [comment]
I was able to solve this on android by saving the file on `ExternalStorageDirectoryPath`. Im not using react-native-share on iOS anymore, although If im correct it worked when I first created a Dir and then generated the file inside that Dir.

**Comment by avencat** [comment]
Hi @RUIFERNANDE5 ! I have the same issue here but I don't understand how you save the file on `ExternalStorageDirectoryPath`, could you please help me there ?

Thank you !

**Comment by avencat** [comment]
@RUIFERNANDE5 I was able to solve the problem by using `rnfs.ExternalStorageDirectoryPath` thank you for the solution! :) I wondered also if you know how to share a vcf via MMS? (When I click on message, I get an error saying that files must be shared via MMS and not SMS... (On Android)

Thank you for your time ! :)

**Comment by RUIFERNANDE5** [comment]
@avencat well, using `react-native-fs` when defining the path where the file should be written you start the path with `RNFS.ExternalStorageDirectoryPath`

**Comment by RUIFERNANDE5** [comment]
Im using `react-native-share` only on android and it doesn't pop the sms / mms option on the share dialog unfortunately. If you find any solution feel free to share with me

**Comment by avencat** [comment]
Ok and you use the `open` method or `shareSingle`? :)

**Comment by avencat** [comment]
@RUIFERNANDE5 I managed to share via `MMS` with the type `text/x-vcalendar` and the `open` method like this:
```javascript
Share.open({
  url: `file://${rnfs.ExternalStorageDirectoryPath}/vcard.vcf`,
  subject: `${data.name + ' ' + data.firstname}`,
  type: 'text/x-vcalendar'
});
```

#### NOTE: The open method is the best option for me as I want the user to be able to share with any application available for this type

**Comment by RUIFERNANDE5** [comment]
@avencat In my case the correct ftype is 'text/xcard' and the one you pointed out throwed an error because it was the incorrect type. Anyway, I was wrong it turns out it pops the message options and its all working as intended. Sorry

**Comment by avencat** [comment]
@RUIFERNANDE5 Ok thank you, but I tried `text/xcard` and my test Android phone won't show the `sms/mms` option so, according to [this page](http://filext.com/file-extension/VCF), I put `text/x-vcalendar` and it works for my case so I think I'll let as it... 😉 

Thank you for sharing with me on that issue, have a good day! 😄

**Comment by prtkkmrsngh** [comment]
@RUIFERNANDE5 @avencat text/x-vcalendar mime-type not allowing to share vcard file to whatsapp. If I share file from explorer then it get shared but not will plugin. Any fix for this?

**Comment by avencat** [comment]
Hi @prtkkmrsngh!

Have you tried putting `text/xcard`? I have no other idea, so no fix... 😕 But if you find one, let us know! 😄

**Comment by prtkkmrsngh** [comment]
Removing type from options is working as intended :+1:

**Comment by avencat** [comment]
@prtkkmrsngh Nice, thanks for the tip!

**Comment by MithleshKumarAndroid** [comment]
permission denied for attachment react native

**Comment by Peretz30** [comment]
for anyone trying to share vcard on both platforms. This method works for me. I am using [RNFetchBlob](https://github.com/joltup/rn-fetch-blob) and [utf8](https://github.com/mathiasbynens/utf8.js)
```javascript
const vCard = `
BEGIN:VCARD
VERSION:3.0
N:Gump;Forrest;;Mr.;
FN:Forrest Gump
ORG:Bubba Gump Shrimp Co.
TITLE:Shrimp Man
PHOTO;VALUE=URI;TYPE=GIF:http://www.example.com/dir_photos/my_photo.gif
TEL;TYPE=WORK,VOICE:(111) 555-1212
TEL;TYPE=HOME,VOICE:(404) 555-1212
ADR;TYPE=WORK,PREF:;;100 Waters Edge;Baytown;LA;30314;United States of America
LABEL;TYPE=WORK,PREF:100 Waters Edge\nBaytown\, LA 30314\nUnited States of America
ADR;TYPE=HOME:;;42 Plantation St.;Baytown;LA;30314;United States of America
LABEL;TYPE=HOME:42 Plantation St.\nBaytown\, LA 30314\nUnited States of America
EMAIL:forrestgump@example.com
REV:2008-04-24T19:52:43Z
END:VCARD
`
const vCardBytes = utf8.encode(vCard);
const vCardBase64 = RNFetchBlob.base64.encode(vCardBytes);
                if (Platform.OS === 'android') {
                    Share.open({
                        url: 'data:text/x-vcard;base64,' + vCardBase64,
                        filename: 'VCard',
                    })
                        .catch(err => { console.log(err) })
                } else {
                    const filepath = RNFetchBlob.fs.dirs.CacheDir + '/vcard.vcf'
                    RNFetchBlob.fs.createFile(filepath, vCardBase64, 'base64').then(async () => {
                        await Share.open({
                            //url: 'data:text/vcard;base64,' + RNFetchBlob.base64.encode(data),
                            url: 'file://' + filepath,
                            //type: 'text/x-vcard',
                            filename: 'VCard',
                        })
                    })
                        .catch(err => {
                            console.log(err)
                        })
                        .finally(() => {
                            RNFetchBlob.fs.unlink(filepath)
                        })
                }
```

**Comment by cristianoccazinsp** [comment]
On iOS, using `shareSingle` and email, iOS will still attach the file URI at the end of the email body rather than including it as an attachment.  Interestingly, using just `open` and selecting the email client will include the attachment successfully, but then the email to address won't be populated.

On Android, the file is added as an attachment just fine. Thoughts? How can we email attachm

**Comment by Rodrigo-P-Angeli** [comment]
> for anyone trying to share vcard on both platforms. This method works for me. I am using [RNFetchBlob](https://github.com/joltup/rn-fetch-blob) and [utf8](https://github.com/mathiasbynens/utf8.js)
> 
> ```js
> const vCard = `
> BEGIN:VCARD
> VERSION:3.0
> N:Gump;Forrest;;Mr.;
> FN:Forrest Gump
> ORG:Bubba Gump Shrimp Co.
> TITLE:Shrimp Man
> PHOTO;VALUE=URI;TYPE=GIF:http://www.example.com/dir_photos/my_photo.gif
> TEL;TYPE=WORK,VOICE:(111) 555-1212
> TEL;TYPE=HOME,VOICE:(404) 555-1212
> ADR;TYPE=WORK,PREF:;;100 Waters Edge;Baytown;LA;30314;United States of America
> LABEL;TYPE=WORK,PREF:100 Waters Edge\nBaytown\, LA 30314\nUnited States of America
> ADR;TYPE=HOME:;;42 Plantation St.;Baytown;LA;30314;United States of America
> LABEL;TYPE=HOME:42 Plantation St.\nBaytown\, LA 30314\nUnited States of America
> EMAIL:forrestgump@example.com
> REV:2008-04-24T19:52:43Z
> END:VCARD
> `
> const vCardBytes = utf8.encode(vCard);
> const vCardBase64 = RNFetchBlob.base64.encode(vCardBytes);
>                 if (Platform.OS === 'android') {
>                     Share.open({
>                         url: 'data:text/x-vcard;base64,' + vCardBase64,
>                         filename: 'VCard',
>                     })
>                         .catch(err => { console.log(err) })
>                 } else {
>                     const filepath = RNFetchBlob.fs.dirs.CacheDir + '/vcard.vcf'
>                     RNFetchBlob.fs.createFile(filepath, vCardBase64, 'base64').then(async () => {
>                         await Share.open({
>                             //url: 'data:text/vcard;base64,' + RNFetchBlob.base64.encode(data),
>                             url: 'file://' + filepath,
>                             //type: 'text/x-vcard',
>                             filename: 'VCard',
>                         })
>                     })
>                         .catch(err => {
>                             console.log(err)
>                         })
>                         .finally(() => {
>                             RNFetchBlob.fs.unlink(filepath)
>                         })
>                 }
> ```

You saved me so much.
