### ISSUE TITLE
Error Invalid directory /Users/node_modules/NativeModules

### ISSUE THREAD

**Issue by paulgessinger** [EstebanFuentealba/react-native-share#13]
I get the following error when running on iOS.

> Unable to resolve module NativeModules from ]...]/node_modules/react-native-share/index.ios.js: Invalid directory /Users/node_modules/NativeModules

I believe this is because of the way you load the NativeModule, maybe they changed something.

**Comment by paulgessinger** [comment]
Ah, I see this was changed in #7.
Did you publish this to NPM yet?

**Comment by Emibob** [comment]
Looks like it hasn't been published - I'm getting the same errors when running on iOS @EstebanFuentealba

**Comment by Mactub07** [comment]
RN 0.20 , IOS-emulator , see the same mistake
