### ISSUE TITLE
You attempted to set the key 'social' with the value

### ISSUE THREAD

**Issue by ahyong87** [EstebanFuentealba/react-native-share#134]
Hi,

i get this error, You attempted to set the key 'social' with the value "twitter" on an object that is meant to be immutable and has been frozen.

![screen shot 2017-06-28 at 2 27 33 pm](https://user-images.githubusercontent.com/758214/27623212-f63b4a9a-5c0d-11e7-912d-80d3a81416f2.png)

**Comment by ataillefer** [comment]
The problem comes from the `SharePage.js` file at line 78 which is probably part of your app since it isn't part of `react-native-share` nor `react-native`.

**Comment by ahyong87** [comment]
i solve the problem already. 

  const shareOptions = {
    title: this.state.ShareTitle,
    message: this.state.ShareMessage,
    url: this.state.ShareUrl,
    subject: this.state.ShareSubject, //  for email
    social: this.state.ShareType
    };

   Share.shareSingle(shareOptions);

**Comment by kenvandemar** [comment]
What's content of ShareType did you declare on this.state.ShareType?

**Comment by pallavisingh1511** [comment]
I'm facing the same issue. I've implemented singleShare for facebook and twitter. 
It works for the first share, but for the second share it throws this error
'You attempted to set the key 'social' with the value'

**Comment by ahyong87** [comment]
@kenvandemar ShareType i pass twitter,facebook,whatsapp

handleFacebookButtonOnClicked(){
this.setstate({ShareType:'facebook'})
setTimeout(() => {
                this.CallShareFunction();
              },300);
}

handleTwitterButtonOnClicked(){
this.setstate({ShareType:'twitter'})
setTimeout(() => {
                this.CallShareFunction();
              },300);
}

CallShareFunction(){
const shareOptions = {
title: this.state.ShareTitle,
message: this.state.ShareMessage,
url: this.state.ShareUrl,
subject: this.state.ShareSubject, // for email
social: this.state.ShareType
};

Share.shareSingle(shareOptions);
}

**Comment by kenpaxtonlim** [comment]
![whatsapp image 2017-07-10 at 5 05 18 pm](https://user-images.githubusercontent.com/25319347/28010608-09671bb6-6592-11e7-9e9d-d7008ecddc1d.jpeg)

I have the same error as well. Is there a specific fix for this?

```
export default class SocialShare extends Component{

  constructor(props){
    super(props)

    this.shareOptions = {
      title: "TCC Promotion",
      message: "Pasta on 20% discount, valid for the rest of time!",
      url: "http://facebook.github.io/react-native/",
      subject: "TCC Promotion" //  for email
    }
  }

  _share = (type) => {
    switch(type){
      case 'phone': //take screenshot
        break;
      case 'wechat': //current module do not support
        break;
      default:
      Share.shareSingle(Object.assign(this.shareOptions, {"social": type})).catch(err => console.log(err))
    }
  }

  render(){
    return(
      <View style={styles.container}>
        <Icon.Button
          name='facebook-official'
          backgroundColor="#3b5998"
          onPress={() => this._share('facebook')}
        >
          Share on Facebook
        </Icon.Button>

        <Icon.Button
          name='twitter-square'
          backgroundColor="#0084b4"
          onPress={() => this._share('twitter')}
        >
          Share on Twitter
        </Icon.Button>

        <Icon.Button
          name='whatsapp'
          backgroundColor="#25d366"
          onPress={() => this._share('whatsapp')}
        >
          Share on WhatsApp
        </Icon.Button>

        <Icon.Button
          name='envelope'
          backgroundColor="#0084b4"
          onPress={() => this._share('email')}
        >
          Share on Email
        </Icon.Button>

        <Icon.Button
          name='mobile'
          backgroundColor="black"
          onPress={() => this._share('phone')}
        >
          Save to Phone
        </Icon.Button>

        <Icon.Button
          name='plus'
          backgroundColor="gray"
          onPress={() => Share.open(this.shareOptions).catch(err => console.log(err))}
          >
            Share more...
          </Icon.Button>
      </View>
    )
  }
}
```

**Comment by hungdev** [comment]
@kenpaxtonlim i get same error

**Comment by hungdev** [comment]
i know the error. it's error when assign object. It can set key when you share a second time. 
i fixed it like this:
`import React, { Component } from 'react'
import {
  Clipboard,
  ToastAndroid,
  AlertIOS,
  Platform
} from 'react-native'
import Share, { ShareSheet, Button } from 'react-native-share'

export default class TestShare extends Component {
  constructor (props) {
    super(props)
    this.state = {
      visible: false
    }
  }

  componentWillMount () {
    this.setState({ shareOptions: this.props.shareOptions })
  }

  onCancel () {
    console.log('CANCEL')
    this.setState({ visible: false })
  }
  onOpen () {
    console.log('OPEN')
    this.setState({ visible: true })
  }
  render () {
    return (
      <ShareSheet visible={this.state.visible} onCancel={this.onCancel.bind(this)}>
        <Button iconSrc={{ uri: TWITTER_ICON }}
          onPress={() => {
            this.onCancel()
            setTimeout(() => {
              Share.shareSingle({
                title: 'Qubikal',
                message: this.state.shareOptions.message,
                url: this.state.shareOptions.url,
                subject: this.state.shareOptions.subject,
                social: 'twitter'
              })
            }, 300)
          }}>Twitter</Button>
        <Button iconSrc={{ uri: FACEBOOK_ICON }}
          onPress={() => {
            this.onCancel()
            setTimeout(() => {
              Share.shareSingle({
                title: 'Qubikal',
                message: this.state.shareOptions.message,
                url: this.state.shareOptions.url,
                subject: this.state.shareOptions.subject,
                social: 'facebook'
              })
            }, 300)
          }}>Facebook</Button>
        <Button iconSrc={{ uri: WHATSAPP_ICON }}
          onPress={() => {
            this.onCancel()
            setTimeout(() => {
              Share.shareSingle({
                title: 'Qubikal',
                message: this.state.shareOptions.message,
                url: this.state.shareOptions.url,
                subject: this.state.shareOptions.subject,
                social: 'whatsapp'
              })
            }, 300)
          }}>Whatsapp</Button>
        <Button iconSrc={{ uri: GOOGLE_PLUS_ICON }}
          onPress={() => {
            this.onCancel()
            setTimeout(() => {
              Share.shareSingle({
                title: 'Qubikal',
                message: this.state.shareOptions.message,
                url: this.state.shareOptions.url,
                subject: this.state.shareOptions.subject,
                social: 'googleplus'
              })
            }, 300)
          }}>Google +</Button>
        <Button iconSrc={{ uri: EMAIL_ICON }}
          onPress={() => {
            this.onCancel()
            setTimeout(() => {
              Share.shareSingle({
                title: 'Qubikal',
                message: this.state.shareOptions.message,
                url: this.state.shareOptions.url,
                subject: this.state.shareOptions.subject,
                social: 'email'
              })
            }, 300)
          }}>Email</Button>
        <Button
          iconSrc={{ uri: CLIPBOARD_ICON }}
          onPress={() => {
            this.onCancel()
            setTimeout(() => {
              if (typeof this.props.shareOptions['url'] !== 'undefined') {
                Clipboard.setString(this.props.shareOptions['url'])
                if (Platform.OS === 'android') {
                  ToastAndroid.show('Link copiado al portapapeles', ToastAndroid.SHORT)
                } else if (Platform.OS === 'ios') {
                  AlertIOS.alert('Link copiado al portapapeles')
                }
              }
            }, 300)
          }}>Copy Link</Button>
      </ShareSheet>
    )
  }
}`

**Comment by kenpaxtonlim** [comment]
@hungdev May I know which part exactly is the fix?

**Comment by hungdev** [comment]
Dont use assign and write like me. Look my shareSingle()

**Comment by kenpaxtonlim** [comment]
@hungdev Thank you very much, it works! :)

**Comment by pigflymoon** [comment]
Change 
Share.shareSingle(Object.assign(this.shareOptions, {"social": type})).catch(err => console.log(err))
to
 Share.shareSingle(Object.assign({},shareOptions, {
                                    "social": "email"
                                })).catch(err => console.log(err));

**Comment by agrawalo** [comment]
I am still getting this error 

[exp] undefined is not an object (evaluating '_reactNative.NativeModules.RNShare.shareSingle')
* null:null in <unknown>
- node_modules/promise/setimmediate/core.js:45:7 in tryCallTwo
- node_modules/promise/setimmediate/core.js:200:23 in doResolve
- node_modules/promise/setimmediate/core.js:66:12 in Promise
* null:null in shareSingle
* components/PreviewImage.js:81:44 in <unknown>
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:262:23 in <unknown>
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:154:6 in _callTimer
- ... 6 more stack frames from framework internals
