### ISSUE TITLE
How to install it on RN 0.20 for Android?

### ISSUE THREAD

**Issue by exoer** [EstebanFuentealba/react-native-share#14]
It appears that the `MainActivity.java` file has changed for ReactNative release 0.19 and 0.20 compared to the documentation in the README. I can't find the `onCreate`-method, so it is not clear how to add the package `.addPackage(new RNSharePackage())`?

**Comment by polacekpavel** [comment]
In your MainActivity.java add package import this way.

in the top of file.
`import cl.json.RNSharePackage;`
and in the code 

``` @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
        new MainReactPackage(),
        new RNSharePackage()        
      );
    }

**Comment by exoer** [comment]
Thank you
