### ISSUE TITLE
[Android] share_text doesn't seem to work

### ISSUE THREAD

**Issue by xiaobuu** [EstebanFuentealba/react-native-share#16]
With both share_text and share_URL defined, only the url is shown in the shared text, is it a bug or the normal behaviour of Android system?

**Comment by udfalkso** [comment]
Seems like it depends where your'e sharing it to.  I find that sharing to Gmail, the share_text shows.  But sharing to twitter, it doesn't.  Seems like some apps use the SUBJECT field and some don't.

**Comment by tgoldenberg** [comment]
Yeah, kind of a let down that the text doesn't share to either Facebook or Twitter

**Comment by mustafapolat** [comment]
For fixing it : 
In this file : 
https://github.com/EstebanFuentealba/react-native-share/blob/master/android/src/main/java/cl/json/RNShareModule.java#L53:L55
Replace the code line 53-54 as below: 
`    if (hasValidKey("share_text", options)) {
      intent.putExtra(Intent.EXTRA_TEXT, options.getString("share_text"));
    }
`
i hope @EstebanFuentealba consider it :)

**Comment by alyssonmessias** [comment]
Thanks @mustafapolat , resolved my problem. My code as below:

 `private Intent createShareIntent(ReadableMap options) {
    Intent intent = new Intent(android.content.Intent.ACTION_SEND);
    intent.setType("text/plain");

    String msg = "";
    String title = "Share";
    if (hasValidKey("title", options)) {
      title = options.getString("title");
      intent.putExtra(Intent.EXTRA_SUBJECT, title);
    }

    if (hasValidKey("share_text", options)) {
      msg += options.getString("share_text");
    }


    if (hasValidKey("share_URL", options)) {
      msg += "\n"+options.getString("share_URL");
    }

    intent.putExtra(Intent.EXTRA_TEXT, msg); 
    
    return intent;
  }`

**Comment by mkdotcom** [comment]
Thanks @alyssonmessias
It should be added to the repo
