### ISSUE TITLE
Share image as opposed to url?

### ISSUE THREAD

**Issue by SharanyaRao91** [EstebanFuentealba/react-native-share#160]
As of now, using react-native-share, when i share to whatsapp/twitter/etc it gets passed as a URL (See attachment). Is it possible to share an image itself? The URL when clicked shows the image but is it possible to share a jpg image, like how you would when you share from the phones camera roll.

RN version : 0.44
node version : v7.10.1

![image](https://user-images.githubusercontent.com/29380959/30453245-3633b336-9966-11e7-900e-b08830c3058e.png)

**Comment by shirbr510** [comment]
I'm currently attempting to do the same.
it seems that it's possible by using either base64 decoding or simply downloading the file locally and pointing it as the url

**Comment by SharanyaRao91** [comment]
I was able to share as image on all except twitter. I used RNFetchBlob to convert the URL to base64 and then shared it. Thanks.

**Comment by ER1011** [comment]
I'm using RN 0.49.5 and I've tried every possible combination of url formats, base64 and not, and I can't get an image to exported. When I use a file uri and try to share via email or text then the email/text open, I see the icon there related to the image (no thumbnail though) but then when I press send no image is actually sent with the email/text message.

**Comment by coryjb** [comment]
Hi there - I posed this in another comment, but here's what's working for me using [react-native-fs](https://github.com/itinance/react-native-fs) to get the base64-encoded version of an image:

```javascript
RNFS.readFile(RNFS.DocumentDirectoryPath + '/previews/test.jpg', 'base64').then((image) => {
  Share.open({
    url: 'data:image/jpeg;base64,' + image,
    type: 'image/jpeg'
  }).catch((err) => {
    // Handle error
    // ...
  });
});
```

**Comment by Haggaish** [comment]
+1

**Comment by giturra** [comment]
@SharanyaRao91 Can you give a code example of this? I still stuck with my code

**Comment by SharanyaRao91** [comment]
convertToBase64(){

        let imagePath = null;
        let image_url_length = this.props.img_url.length;

        RNFetchBlob
            .config({
                fileCache : true
            })
            .fetch('GET', this.props.img_url)
            // the image is now dowloaded to device's storage
            .then((resp) => {
                // the image path you can use it directly with Image component
                imagePath = resp.path();
                return resp.readFile('base64')
            })
            .then((base64Data) => {
                // here's base64 encoded image
                if(this.props.img_url.substring(image_url_length-3,image_url_length) === 'mp4')
                    base64Data = 'data:video/mp4;base64,' + base64Data;
                else
                    base64Data = 'data:image/png;base64,' + base64Data;

                this.setState({base64Image: base64Data});
                // remove the file from storage
                return fs.unlink(imagePath)
            })
    }

getShareSheet(){
	
        let shareImageBase64 = {
                    message: "Hello",
                    url: this.state.base64Image
        };

        return( <ShareSheet visible={this.state.shareSheetVisible} style={{marginTop:100,zIndex:1000}}onCancel={this.onCancel.bind(this)}>
	
	<Button iconSrc={{ uri: WHATSAPP_ICON }}
                    onPress={()=>{
                        Share.shareSingle(Object.assign(shareImageBase64, {
                            social : "whatsapp"
                        })).catch(err=>console.log(err));
            }}>Whatsapp</Button>

    <Button
                onPress={()=>{
              this.onCancel();
                          }}>Cancel</Button>

    </ShareSheet>)
    }


}
