### ISSUE TITLE
[iPad] App  terminating when try to open UIPopoverPresentationController

### ISSUE THREAD

**Issue by Max93** [EstebanFuentealba/react-native-share#17]
Terminating app due to uncaught exception 'NSGenericException', reason: 'UIPopoverPresentationController (<_UIAlertControllerActionSheetRegularPresentationController: 0x7ce06ba0>) should have a non-nil sourceView or barButtonItem set before the presentation occurs.

**Comment by Max93** [comment]
I have found this http://stackoverflow.com/a/27189994/2110721

**Comment by burnsting** [comment]
Did you manage to fix this by any chance?

**Comment by Sexycrets** [comment]
Any update on this?

**Comment by sf577** [comment]
Ive opened a Pull Request to add support for this #24

**Comment by burnsting** [comment]
Work for me, thanks for the fix @sf577 !

**Comment by sf577** [comment]
@EstebanFuentealba Can npm be updated with the latest version and then we can close this issue
