### ISSUE TITLE
Sharing an Image

### ISSUE THREAD

**Issue by CreativeManix** [EstebanFuentealba/react-native-share#18]
How Can I share an Image on Android?

**Comment by CreativeManix** [comment]
I have forked and added some support for Image sharing for Android. Tested with whatsapp, FB, gmail it works fine. It is also required to add  WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE Permissions.

I am not a Java Programmer so the code is not well organised, so I didn't sent a pull.

https://github.com/CreativeManix/react-native-share

**Comment by pewh** [comment]
Good job @CreativeManix! I think it should be merged. Out of curiosity, is it work with Instagram?

**Comment by pewh** [comment]
Have tested it and it's work :)

**Comment by superandrew213** [comment]
Just submitted a [pr](https://github.com/EstebanFuentealba/react-native-share/pull/34) for this for android and iOS.

**Comment by manjeet-dobble** [comment]
just wanted to if solution by @CreativeManix  get merged or not?

**Comment by himelnagrana** [comment]
Curious about the same thing ...

> just wanted to know if solution by @CreativeManix get merged or not?

**Comment by sibelius** [comment]
@CreativeManix can u send the pr again?
