### ISSUE TITLE
Sharing base64 image is not working anymore.

### ISSUE THREAD

**Issue by kbrk** [EstebanFuentealba/react-native-share#184]
Hello,
I am developing on android. My react-native version is **0.42** I'm using this package for sharing screen view. The data I want to share is being converted to base64. 

```
...
const uri = "data:image/png;base64,...";

                Share.open({
                    title: "Title",
                    message: "Message",
                    url: uri,
                    subject: "Mail subject"
                })
...
```

This process was working properly on whatsapp, facebook and email before. 
However, now, when I tried on whatsapp the response is '_Sharing failed. Please try again_', on facebook I'm getting an empty text area without sharing options and on email I'm getting the text typed options except for the image.

Do you have any suggestion? Thank you.

**Comment by piubellofelipe** [comment]
```
let options = {
                url: `data:image/png;base64,` + base64Data,
                type: 'image/png',
                message: '',
                title: ''
            };
            Share.open(options).then(response => {
                ... 
```

is working for me, maybe the type field is important? did not try without it

**Comment by kbrk** [comment]
@piubellofelipe   thank you but it is not working.

**Comment by kbrk** [comment]
_targetSdkVersion_ of the project that I am working on has been 23. With version 23 system requires
 **Overlay permission** and it may interfere to use of the other applications. When I changed the sdkVersion to _22_ in  _android/app/buld.gradle_ and _android/app/src/main/AndroidManifest.xml_ sharing worked normally again.

**Comment by MrHazimAli** [comment]
@kbrk , any idea to make it work using version 23 ?

**Comment by manujbahl** [comment]
Does this work on iOS? I am trying on ios and fb sharing does not bring up the message. It only shows the image. 

Here is my code. 

```
var shareImageBase64 = {
                                type: 'image/png',
                                title: "React Native",
                                message: "Hi There",
                                url: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAd4klEQVR42u1d....',
                                subject: "Share Link"
                              };

                           
                                await Share.open(shareImageBase64);
```

**Comment by MateusAndrade** [comment]
#536
