### ISSUE TITLE
Possible Unhandled Promise Rejection Cannot read property 'shareSingle' of undefined (Android)

### ISSUE THREAD

**Issue by Benorb** [EstebanFuentealba/react-native-share#190]
Hello,
When i try to activate shareSingle function on android , it dosn't work and write on log Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'shareSingle' of undefined .

I did also the automatic and after that didnt work i made also the manual installation.

The problem is that inside the package code there is a call to **NativeModules.RNShare**.
And this is undefined !
Sombody know why?
![image](https://user-images.githubusercontent.com/33088451/32417445-934bde02-c262-11e7-9bfa-f962f8db3628.png)

My code is a copy of the code on the README.

Waiting for help.
Thanks,

**Comment by nikhilninawe** [comment]
I am also facing the same issue. You got any solution?

**Comment by joaquincamara** [comment]
You have to do the manual configuration from android:

Android
npm install react-native-share --save
Open up android/app/src/main/java/[...]/MainApplication.java
Add import cl.json.RNSharePackage; to the imports at the top of the file
Add new RNSharePackage() to the list returned by the getPackages() method
Append the following lines to android/settings.gradle:

include ':react-native-share'
project(':react-native-share').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-share/android')
Insert the following lines inside the dependencies block in android/app/build.gradle:

  compile project(':react-native-share')

I dont have that problem know but the method still not working

sorry for my bad english.

**Comment by sibelius** [comment]
this is a problem with a wrong link

**Comment by joaquincamara** [comment]
Where ? and wich one ? @sibelius

**Comment by jgcmarins** [comment]
@joaquincamara , when linking this lib to your project.
`react-native-link` is tricky.

**Comment by JsonAveza** [comment]
I am also facing the same issue. You got any solution?

**Comment by mikehardy** [comment]
@JsonAveza use the example, to prove everything works, then adapt your code slowly in the same style to match it. Probably a problem with linking. Might be that you used a Promise returning object outside of an async/await or .then().catch() structure
