### ISSUE TITLE
singleShare is not working for Twitter, Whatsapp, etc.

### ISSUE THREAD

**Issue by luco** [EstebanFuentealba/react-native-share#193]
When I try to use `singleShare`, it doesn't work with installed apps. E.g.:

Tried to share via Whatsapp, it opens AppStore to download WhatsApp, but the app is already installed.

Also on Twitter, it opens the Safari on twitter.com.

Thoughts?

Thanks

**Comment by jgcmarins** [comment]
hey @luco how did you solve that?
