### ISSUE TITLE
Runtime error: Attempt to invoke virtual method 'android.content.res.XmlResourceParser

### ISSUE THREAD

**Issue by EyalSi** [EstebanFuentealba/react-native-share#201]
I'm getting the following error when using version 1.0.24 (after adding the provider).
Did anyone face this? (it was working with the previous version...)

10x!!!

`Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.PackageItemInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
parsePathStrategy
    FileProvider.java:583
getPathStrategy
    FileProvider.java:557
getUriForFile
    FileProvider.java:399
getURI
    ShareFile.java:135
open
    ShareIntent.java:49
open
    GenericShare.java:18
open
    RNShareModule.java:50
invoke
    Method.java
invoke
    JavaMethodWrapper.java:374
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:751
dispatchMessage
    Handler.java:95
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:154
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:761
`

**Comment by EyalSi** [comment]
Rebuild solved this one.
For those coming from version 1.0.23 to 1.0.24, you need to:
1. Add to .\android\app\src\main\AndroidManifest.xml, in <application> section:
```
<provider
  android:name="android.support.v4.content.FileProvider"
  android:authorities="${applicationId}.provider"
  android:grantUriPermissions="true"
  android:exported="false">
</provider>
```
2. Add to .\android\app\src\main\java\com\anashim\MainApplication.java
(you already added the package when you installed this):
```
import cl.json.ShareApplication;
...
public class MainApplication extends Application implements ReactApplication, ShareApplication  {
...
  @Override
  public String getFileProviderAuthority() {
         return "${applicationId}.provider";
  }  
```

**Comment by jgcmarins** [comment]
Hello @EyalSi.
Thanks for feedback. Could you please send a PR to update README with this information?
Thanks.

**Comment by jgcmarins** [comment]
Never mind. It's already done here: https://github.com/EstebanFuentealba/react-native-share#android
Thanks anyway.

**Comment by filipef101** [comment]
@EyalSi I have the same issue, applied both codes and still the same

**Comment by filipef101** [comment]
I get a crash now when I add the code to manifest

**Comment by jgcmarins** [comment]
@filipef101 could you provide more information, please?

**Comment by filipef101** [comment]
@jgcmarins Do i need:
`<meta-data
				android:name="android.support.FILE_PROVIDER_PATHS"
				android:resource="@xml/filepaths"
				tools:replace="android:resource"/>`
?
If so how do I set the paths, when I place the code on the manifest the app crashes immediately

**Comment by filipef101** [comment]
I just want to share a base64 image

**Comment by jgcmarins** [comment]
@filipef101 version 1.0.23 is working fine

**Comment by filipef101** [comment]
I had to put on main application part the package name hardcode and with an if debug since my debug package name ends in .debug and in manifest left it fetching from graddle and no issue, after all I wasn't sharing a base64, and 1.0.23 doesn't work on andoird Oreo

**Comment by filipef101** [comment]
Also needed the code above I asked and a paths.xml with the download folder path, as per the issue #200

**Comment by andrei-m-code** [comment]
1.1.0 Same issue Oreo. Works good on L

**Comment by prgpascal** [comment]
My issue was I had different package names for different build types (ex. ".debug"). So, hard-coding the package name in `getFileProviderAuthority()` without checking the build type at runtime was not a solution.
I came up with this solution that works for me:
```java
@Override
public String getFileProviderAuthority() {
   return this.getPackageName() + ".provider";
}
```

**Comment by jgcmarins** [comment]
yep, this is the 6th step on [Android install instructions](https://github.com/react-native-community/react-native-share/blob/master/README.md#android-install)

**Comment by nichikayoshida** [comment]
> My issue was I had different package names for different build types (ex. ".debug"). So, hard-coding the package name in `getFileProviderAuthority()` without checking the build type at runtime was not a solution.
> I came up with this solution that works for me:
> 
> ```java
> @Override
> public String getFileProviderAuthority() {
>    return this.getPackageName() + ".provider";
> }
> ```

this worked for me

**Comment by Shanie1331** [comment]
@EyalSi @jgcmarins @filipef101 @prgpascal @heracek please help!
Android 8.1.0, api 27...

build.gradle(module app)


```
android {
    compileSdkVersion 27
    buildToolsVersion '28.0.3'
}
build.gradle (project: xxx)

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 16
        compileSdkVersion = 27
        targetSdkVersion = 26
        supportLibVersion = "27.1.1"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        classpath 'com.google.gms:google-services:4.0.1'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        mavenLocal()
        jcenter()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
    }
}


task wrapper(type: Wrapper) {
    gradleVersion = '4.4'
    distributionUrl = distributionUrl.replace("bin", "all")
}

subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support'
                    && !details.requested.name.contains('multidex') ) {
                details.useVersion "27.1.1"
            }
        }
    }
}

```

Android.manifest...

```
<uses-permission android:name="android.permission.INTERNET" />
<uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
<uses-permission android:name="android.permission.READ_PHONE_STATE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />

<application
  android:name=".MainApplication"
  android:label="@string/app_name"
  android:icon="@mipmap/ic_launcher"
  android:allowBackup="false"
  android:theme="@style/AppTheme">
  <activity
    android:name=".MainActivity"
    android:label="@string/app_name"
    android:configChanges="keyboard|keyboardHidden|orientation|screenSize"
    android:windowSoftInputMode="adjustPan">
      <intent-filter>
          <action android:name="android.intent.action.SEND" />
          <category android:name="android.intent.category.DEFAULT" />
          <data android:mimeType="text/plain" />
          <data android:mimeType="image/*" />
      </intent-filter>
    <intent-filter>
        <action android:name="android.intent.action.MAIN" />
        <category android:name="android.intent.category.LAUNCHER" />
        <action android:name="android.intent.action.DOWNLOAD_COMPLETE"/>
    </intent-filter>
  </activity>
  <activity android:name="com.facebook.react.devsupport.DevSettingsActivity" />
    <provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.fileprovider"
        android:grantUriPermissions="true"
        android:exported="false">
        <meta-data
            android:name="android.support.FILE_PROVIDER_PATHS"
            android:resource="@xml/file_paths"/>
    </provider>
</application>

```

I am taking permissions from android like this : ----->

```
if(Platform.OS ==='android'){try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE,
        {
          title: 'Cool Photo App Camera Permission',
          message:
            'Cool Photo App needs access to your camera ' +
            'so you can take awesome pictures.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can READ camera');
      } else {
        console.log('Camera permission denied');
      }
    } catch (err) {
      console.warn(err);
    }
    try {
      const granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE,
        {
          title: 'Cool Photo App Camera Permission',
          message:
            'Cool Photo App needs access to your camera ' +
            'so you can take awesome pictures.',
          buttonNeutral: 'Ask Me Later',
          buttonNegative: 'Cancel',
          buttonPositive: 'OK',
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        console.log('You can WRITE camera');
      } else {
        console.log('Camera permission denied');
      }
    } catch (err) {
      console.warn(err);
    }}
```

this is what I am doing ------>

 ```
let base64Str = res;
            const fs = RNFetchBlob.fs
            const dirs = RNFetchBlob.fs.dirs;
            let imageLocation = dirs.DownloadDir +'/'+'reactNew.png';
            fs.writeFile(imageLocation, base64Str, 'base64');
            console.log(imageLocation)
            // RNFetchBlob.fs.scanFile([ { path : imageLocation } ])
            RNFetchBlob.fs.readFile(imageLocation, 'base64')
              .then((res) => {
                const URL = "data:image/png;base64,"+res;
                let shareOptions = {
                  // title: "React Native Share Example",
                  // message: "Check out this photo!",
                  url: URL,
                  // url: res,
                  type: 'image/png',
                  // subject: "Check out this photo!"
                }
                Share.open(shareOptions)
                  .then((result) => console.log('result:', result))
                  .catch(err => console.log('err', err))
                  console.log("scan file success")
              })
              .catch((err) => {
                console.log("scan file error")
              })
```
Response in debugger is :

> /storage/emulated/0/Download/reactNew.png ------> console.log(imageLocation)
> 
> scan file success ------> console.log("scan file success")
> 
> err {error: "Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference"} ---------> .catch(err => console.log('err', err))
