### ISSUE TITLE
'RCTBridgeModule.h' file not found

### ISSUE THREAD

**Issue by mcnamee** [EstebanFuentealba/react-native-share#21]
Hi, when I switch build configuration to 'Release', I get the following error:
`'RCTBridgeModule.h' file not found`

This is in Xcode, I'm trying to run on an actual device

**Comment by mcnamee** [comment]
Thanks!

**Comment by hongri** [comment]
@mcnamee have you fixed your bug? I met the same situation too.

**Comment by mcnamee** [comment]
Hi @hongri - yes this did resolve the issue at the time.
