### ISSUE TITLE
[Android]: Share.open does not share image in twitter

### ISSUE THREAD

**Issue by nikhiltekwani09** [EstebanFuentealba/react-native-share#213]
Cannot see image when sharing image on twitter through share.open. I m sending local file uri in url. Also this issue is occurring only in android.

**Comment by jgcmarins** [comment]
@nikhiltekwani09 could you provide more information, please?

**Comment by nikhiltekwani09** [comment]
@jgcmarins I have written a very basic code where I try to share an image to twitter using Share.open or Share.singleShare and provide the local path of the file in url. The image is sharable on facebook but not on twitter.

**Comment by jgcmarins** [comment]
@nikhiltekwani09 did you solve it?

**Comment by nikhiltekwani09** [comment]
@jgcmarins yes

**Comment by jgcmarins** [comment]
how?

**Comment by Sangrene** [comment]
God... People sending issue without code & just saying that they solved it without giving solution...

**Comment by jgcmarins** [comment]
yep, unfortunately :(

**Comment by harrie006** [comment]
@nikhiltekwani09 Hi how did you resolved this?

**Comment by harrie006** [comment]
Resolved.
//for more than one base64 image 
const shareOptions = {
  title: 'Title',
  message: 'Message',
  urls: reviewShare.state.blobArr
};

// when only one base64 image
shareOptions = {
    title: 'Title',
    message: 'Message',
    url: reviewShare.state.blobArr[0],
  };

Share.open(shareOptions)
.then((res) => { console.log(res) })
.catch((err) => { err && console.log(err); });
