### ISSUE TITLE
IOS Share base64 image on twitter not working

### ISSUE THREAD

**Issue by timhorwood** [EstebanFuentealba/react-native-share#223]
Hi,
Has anyone experienced issues sharing a base64 image via twitter on IOS? Works fine for Facebook but the image just doesn't show for Twitter. It did show one time however but won't show again. I am using the base64 of an image created by taking a snapshot of a view.

Thanks,

**Comment by Mavenic** [comment]
@timhorwood Have you got any answer on how to do that?

**Comment by MateusAndrade** [comment]
> @timhorwood Have you got any answer on how to do that?

I don't know if you support Twitter out of the box, but looking at their [implementation](https://stackoverflow.com/questions/14664763/android-sharing-on-twitter).
