### ISSUE TITLE
attempt to invoke interface method 'boolean com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by profiVideos** [EstebanFuentealba/react-native-share#229]
Installed this module today.  Followed all the steps to add module to Android manually (very carefully)! :-)
Running on RN0.54 (most current) on an Android 7.1.1 Emulator.
Share.open(shareOptions) is working properly
Share.shareSingle(shareOptions) - NOT WORKING!
const shareOptions = {
  title: 'Excellent Share',
  message: 'See it now on your favorite social media',
  url: 'http://facebook.github.io/react-native/',
  subject: 'Shared Drop from your friend', //  for email
  social: 'whatsapp' 
};

BTW: Same error message when I used published example method to invoke share (i.e.
                Share.shareSingle(Object.assign(shareOptions, {
                  "social": "whatsapp"
                }));
Obviously without the social: whatsapp repeated.

![screenshot_1521761832](https://user-images.githubusercontent.com/33458533/37804163-5f23ebfa-2e33-11e8-9a27-bdf265ce109b.png)

Anyone have any ideas?

**Comment by greatdg** [comment]
To fix this error (https://github.com/RingierAG/react-native-share/commit/ab6b73d2da58b5745a2dc8f71057a4373e6ece3a)

**Comment by profiVideos** [comment]
Yes!  That works.  Thank you very much!

**Comment by jgcmarins** [comment]
hey @greatdg could you send a PR?

**Comment by greatdg** [comment]
@jgcmarins done! https://github.com/EstebanFuentealba/react-native-share/pull/230
