### ISSUE TITLE
why not find libRNShare.a file

### ISSUE THREAD

**Issue by MrPluto** [EstebanFuentealba/react-native-share#3]
why not find libRNShare.a file

**Comment by avishayil** [comment]
+1 on this

**Comment by asommer70** [comment]
Here's what I did to enable the libRNShare.a file and be able to add the Share dialog.

* Open XCode.
* Right click on **Libraries** > Click Add Files To "YOUR PROJECT NAME".
* Browse to your project folder/node_modules/react-native-share and select RNShare.xcodeproj.
* This will add RNShare.xcodeproj under the Libraries and if you expand the library and expand the **Products** folder you should see the **libRNShare.a** file in red.
* Next, click the **main.jsbundle** file under the main project folder in XCode.
* Click the **Build Phases** tab.
* Expand **Compile Sources** and click the **"+"** button.
* Choose the **libRNShare.a** file under **RNShare.xcodeproj**

Hope that helps.

Also, I applied the suggested fix in [#6](https://github.com/EstebanFuentealba/react-native-share/issues/6) before things would build with React Native 0.16.

**Comment by willhalling** [comment]
Hi @asommer70 - I followed your steps but RNShare.xcodeproj isn't available after clicking on the "+" button in Compile Sources - so I can't add libRNShare.a.

Any ideas?

**Comment by asommer70** [comment]
@willhalling I don't find it now too.  Could be something with the XCode version.  Can you try the Share button and let me know if it works?

**Comment by willhalling** [comment]
Thanks for quick response @asommer70. I tried the share button but get an error when calling the share function: undefined is not an object nativeRNShare.open

<img width="315" alt="screen shot 2016-03-08 at 09 17 59" src="https://cloud.githubusercontent.com/assets/3502457/13597152/bafd220e-e50e-11e5-9b1c-91c6066f2811.png">

**Comment by asommer70** [comment]
@willhalling When you get a chance try this:

* Select the **RNSHare.xcodeproj** entry in under **Libraries** in the folder view.
* Click the **Build Phases** tab.
* Expand the **Compile Sources**.
* Click the **"+"** button at the bottom.
* Select **libRNShare.a** under **Products** then click the **Add** button.
* Then build and test out the share button.

Hopefully that will get things fixed up, but let me know how it turns out.

**Comment by yusufseyrek** [comment]
hi there, i have same issue. Libraries -> RNSHare.xcodeproj -> libRNShare.a is red. Also i get "RCTBridgeModule.h" not found error.

**Comment by MrPluto** [comment]
any idea? i got the same issue
