### ISSUE TITLE
android build failed

### ISSUE THREAD

**Issue by 42void** [EstebanFuentealba/react-native-share#32]
Could not compile settings file '/Users/.../android/settings.gradle'.
> startup failed:
  settings file '/Users/.../android/settings.gradle': 2: expecting EOF, found '=' @ line 2, column 73.
     act-native-share').projectDir = new File
                                                  ^

**Comment by cusackd** [comment]
Having a similar issue here, was there a resolution?

**Comment by winfredselwyn** [comment]
@cusackd 

Make sure 'project' is on a new line, like this :

include ':react-native-share'
project(':react-native-share').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-share/android')
