### ISSUE TITLE
Android - Emulator shows wrong share component?

### ISSUE THREAD

**Issue by kfiroo** [EstebanFuentealba/react-native-share#36]
![image](https://cloud.githubusercontent.com/assets/284636/16626403/63de2f52-43b1-11e6-9f9d-c61f93ecd85b.png)

Hey,
I get this view when calling Share.open(...)
Any idea why?
Is it an Emulator issue?

* didn't try on device yet

Great job btw :)

**Comment by mcatmos** [comment]
Same issue to me.

**Comment by kfiroo** [comment]
@EstebanFuentealba I'm still seeing this as well, any advice?
