### ISSUE TITLE
Feature request - Return selected share method to client

### ISSUE THREAD

**Issue by kfiroo** [EstebanFuentealba/react-native-share#37]
react-native ActionSheetIOS.showShareActionSheetWithOptions api returns the method used to share the item to the success callback, anyway to add this functionality to this library as well?

I'm not familiar with objective-c or Java so unfortunately it will be hard for me to provide a PR :(

I can do with some guidance too and try to get a PR with some help though..

Thanks

**Comment by kfiroo** [comment]
IOS seem to not call the callback at all? is that a bug or by design?

**Comment by jburich** [comment]
I recently noticed this as well, I don't think there is any way for the call back to ever get called with the exception of a catastrophic failure on Android. I intend to implement a PR with the call back. Probably in my teams next sprint we'll need this so it'll probably be 2-3 weeks before I get to it.

**Comment by EstebanFuentealba** [comment]
I work in a new version with more features, I implementing ActionSheetIOS for IOS, today or tomorrow I'll upload a commit
