### ISSUE TITLE
iOS: Facebook fields are not prepopulated, but Twitter fields are

### ISSUE THREAD

**Issue by dwilt** [EstebanFuentealba/react-native-share#39]
Here's my code:

```javascript
share() {
    var { url, title } = this.props,
        params = {
            share_text: `Check out this awesome thing.`,
            share_URL: url,
            title
        };

    RNShare.open(params,(e) => {
        console.log(e);
    });
}
```
On Twitter, it works:
![img_4967](https://cloud.githubusercontent.com/assets/1065539/16746774/ce00385e-4770-11e6-849b-7cd8ef37426d.PNG)

But on Facebook, they're empty. Also, the image doesn't post. Any ideas?
![img_4968](https://cloud.githubusercontent.com/assets/1065539/16746809/f7e30304-4770-11e6-8c53-8e5bffbe7545.PNG)

**Comment by pavb74** [comment]
+1

**Comment by EstebanFuentealba** [comment]
Hi, This issue is going to be closed because Facebook does not support pre-filling the message for users as seen in their Policy  D:
https://developers.facebook.com/policy/#socialplugins


Regards!

**Comment by dwilt** [comment]
@EstebanFuentealba Fair, but Twitter is actually populating (it seems) Facebook's field when sharing a tweet. See attached image. Would this actually be against their policy as well?

![img_4999](https://cloud.githubusercontent.com/assets/1065539/17266337/c8bdfda6-55ab-11e6-9c23-3f0511ad5b92.PNG)

If this isn't considered "prepopulating", what would it be considered?

**Comment by EstebanFuentealba** [comment]
those are the OG tags of url but message isnt permited in fb

**Comment by bbc4468** [comment]
Looks like Hashtags are still supported. You can pass hashtags in the message field and facebook does read it.
