### ISSUE TITLE
not working on android - undefined is not an object

### ISSUE THREAD

**Issue by logileifs** [EstebanFuentealba/react-native-share#40]
I followed the example in the readme (tried both manual installation and automatic) and no matter what I do, when I press the share button Share.open always fails with:
`undefined is not an object (evaluating '_reactNativeShare2.default.open')`

building on Ubuntu 14.04 64-bit and running on Android 5.0.1

**Comment by jeromegrosse** [comment]
Works perfectly for me wth React Native 0.29.2.

**Comment by logileifs** [comment]
![gifrecord_2016-07-18_175436](https://cloud.githubusercontent.com/assets/2317815/16925119/3e537d90-4d12-11e6-80ed-8e4af5f51f77.gif)

**Comment by logileifs** [comment]
If anyone has any idea what the problem is I will be happy to fix it myself but I don't have a clue where to start looking for the problem

**Comment by levito** [comment]
Since react native 0.29, you have to apply the adjustments to MainApplication.java, not MainActivity.java. See https://github.com/facebook/react-native/releases/tag/v0.29.0.

The installation via rnpm link doesn't do that at the moment.

**Comment by logileifs** [comment]
@levito so what should MainApplication.java look like for this to work ?

**Comment by EstebanFuentealba** [comment]
Yes, rnpm link doesn't work. In React Native >= 0.29 you need:

## Android

1. `npm install react-native-share --save`
2. Open up `android/app/src/main/java/[...]/MainApplication.java`
  - Add `import cl.json.RNSharePackage;` to the imports at the top of the file
  - Add `new RNSharePackage()` to the list returned by the `getPackages()` method
3. Append the following lines to `android/settings.gradle`:
  	```
  	include ':react-native-share'
  	project(':react-native-share').projectDir = new File(rootProject.projectDir, 	'../node_modules/react-native-share/android')
  	```
4. Insert the following lines inside the dependencies block in `android/app/build.gradle`:

    	```
        compile project(':react-native-share')
    	```

**Comment by logileifs** [comment]
@EstebanFuentealba it works with these instructions, thanks :+1:
