### ISSUE TITLE
Possible Unhandled Promise Rejection (id: 0)

### ISSUE THREAD

**Issue by macuna** [EstebanFuentealba/react-native-share#59]
I'm trying to implement the simple sharing

`import Share, {ShareSheet, Button} from 'react-native-share';`

```
<TouchableHighlight onPress={() => {
     Share.open({
        title: "React Native",
        message: "Hola mundo",
        url: "http://facebook.github.io/react-native/"
      })
}}>
      <Text> Share </Text>
</TouchableHighlight>
```

But I got this error:

09-07 11:07:45.829  3037  5393 W ReactNativeJS: Possible Unhandled Promise Rejection (id: 0):
09-07 11:07:45.829  3037  5393 W ReactNativeJS: undefined is not an object (evaluating '_reactNative.NativeModules.RNShare.open')

Any advice ?

**Comment by macuna** [comment]
Don't worry my fault,  I didn't add this new RNSharePackage() on MainApplication.java.

Thanks!

**Comment by stief510** [comment]
I am having this problem and I have including it into MainApplication.java

**Comment by wootwoot1234** [comment]
I'm having this issue too but on iOS.  What did you guys do to solve it?

**Comment by ananyacleetus** [comment]
Has anyone figured this out?
