### ISSUE TITLE
NativeModules error on iOS in rn 0.16.0

### ISSUE THREAD

**Issue by samuelkraft** [EstebanFuentealba/react-native-share#6]
Unable to resolve module NativeModules from projectdirectory/node_modules/react-native-share/index.ios.js: Invalid directory /Users/node_modules/NativeModules

**Comment by lifuzu** [comment]
+1

**Comment by lifuzu** [comment]
Hi @samuelkraft I had a PR #7 to fix the problem. For temporary solution, you can replace your package.json:
"react-native-share": "^1.0.4",
=>
"react-native-share": "lifuzu/react-native-share"

Hope can help you.

**Comment by samuelkraft** [comment]
Thanks, your PR works! Hopefully this will be merged soon.

**Comment by kyle-ssg** [comment]
Can this be merged please ? :+1:

**Comment by mrcritical** [comment]
+1

**Comment by dangnelson** [comment]
+1

**Comment by willhalling** [comment]
+1
