### ISSUE TITLE
Empty content while using whatsapp single share.

### ISSUE THREAD

**Issue by rohitgoyal** [EstebanFuentealba/react-native-share#87]
Hi
This is how I am trying to use single share for whatsapp.

```
whatsappInvite(){
  let shareOptions = {
	title: "YO",
	message: "Join me in this game",
	url: "www.google.com",
	subject: "Join me in this game" //  for email
  };
    setTimeout(() => {
      Share.shareSingle(Object.assign(shareOptions, {
        "social": "whatsapp"
      }));
    },300);
}
```

This successfully opens the whatsapp app to select the people i want this to send to. But when i select the person I want the content send to in the next screen the content is null. There is absolutely nothing. 
General Share works fine though, 

Look at the picture below for the result of above code. 

![img_5472](https://cloud.githubusercontent.com/assets/4688513/21183288/3ec35792-c22d-11e6-865d-0683884502f8.PNG)

**Comment by aakashrai1** [comment]
In RNShare/social/WhatsAppShare.m file 

Replace the below code and see if this works.
--------------------------------------------------------------------------------------------
NSString *text = [RCTConvert NSString:options[@"message"]];
text = [text stringByReplacingOccurrencesOfString:@":" withString:@"%3A"];
text = [text stringByReplacingOccurrencesOfString:@"/" withString:@"%2F"];
text = [text stringByReplacingOccurrencesOfString:@"?" withString:@"%3F"];
text = [text stringByReplacingOccurrencesOfString:@"," withString:@"%2C"];
text = [text stringByReplacingOccurrencesOfString:@"=" withString:@"%3D"];
text = [text stringByReplacingOccurrencesOfString:@"&" withString:@"%26"];
        
NSString * urlWhats = [NSString stringWithFormat:@"whatsapp://send?text=%@", text];
NSURL * whatsappURL = [NSURL URLWithString:urlWhats];

---------------------------------------------------------------------------------------------

Please append option url string with the text string if needed.
