### ISSUE TITLE
doesn't work with React Native v0.40

### ISSUE THREAD

**Issue by ja-ah** [EstebanFuentealba/react-native-share#92]
duplicate interface definition for class 'RCTBridge'
![screen shot 2017-01-05 at 12 37 41 am](https://cloud.githubusercontent.com/assets/16236589/21656269/40c230a0-d2df-11e6-8822-1a4e10829b05.png)

**Comment by pratih** [comment]
+1

**Comment by acornejo** [comment]
+1

**Comment by jsappme** [comment]
+1
