### ISSUE TITLE
Share.shareSingle shares a base 64 image as a text for twitter

### ISSUE THREAD

**Issue by baderahmed** [EstebanFuentealba/react-native-share#96]
By using Share.open to share an image base 64, the image is shared, but with Share.singleShare it is shared as a text !

**Comment by sibelius** [comment]
@baderahmed did u solve your issue?

**Comment by nidzola** [comment]
any progress on this?

**Comment by tavour-frank** [comment]
@baderahmed @sibelius @nidzola Just tested a fix locally for android. The issue is using an old package name for twitter in TwitterShare.java The new package name is now `com.twitter.android` as opposed to `com.twitter`. Haven't investigated iOS yet
