### ISSUE TITLE
Share a base64 image doesn't work on WhatsApp

### ISSUE THREAD

**Issue by faxioman** [EstebanFuentealba/react-native-share#97]
I'm trying to share a base 64 image on WhatsApp, but only the message is displayed.
I'm using the simple Share.open method on iOS.

**Comment by bjacog** [comment]
I am experiencing the same problem.

**Comment by viniciusbo** [comment]
@faxioman @bjacog were you guys able to workaround that problem?

**Comment by bjacog** [comment]
@viniciusbo not yet, I have chosen to use the built in Share api instead.

**Comment by faxioman** [comment]
@viniciusbo maybe I'm wrong, but I think the problem is in Whatsapp. If I send only the image without any text, I can see it correctly. If I send image with text, all app with share support are working correctly... except whatsapp.

**Comment by viniciusbo** [comment]
@faxioman very well pointed. I ended up saving the file and passing the location as parameter instead of base64.

**Comment by faxioman** [comment]
I think I can close this issue.

**Comment by gerardus1995** [comment]
I have the same problem only in Ios , in android it works perfectly.

**Comment by pckz** [comment]
@bjacog hey! I'm developing a button that share the image in base64 directly to whatsapp. I saw you said that you used the Share api to do that. Can you explain me how you did? thanks very much.. I'm learning react native and I don't know how to figure out to share an image directly to whatsapp (the app must be opened directly, without share menu displaying) help please

**Comment by bjacog** [comment]
Hi,

The best way IMHO is to share a url that points to the image you want to
share. So upload the image to your server and share the URL via the
standard share lib.

Regards / Groete
Jaco

**Comment by pckz** [comment]
Thanks,

I solved the problem making a own Native Module in Xcode, that download the image and put in share options so in whatsapp  only I need select people and after that show  me the image file to send :D

Thanks anyway!!

**Comment by gustavofuhr** [comment]
I confirmed that this problem still exists in iOS, why the issue is closed?

**Comment by faxioman** [comment]
@gustavofuhr because, I think, it's an issue related to WhatsApp.

**Comment by gustavofuhr** [comment]
@faxioman You're right. But, would not be better to remove/ignore the message field if whatsApp is selected? Or is that something that cannot be controlled by the lib? In my application, I removed the message completely, so whatsapp works ok. :-)

**Comment by faxioman** [comment]
@gustavofuhr is it more important the message or the image? I think that is not possible to decide if may be correct to remove the message or the text ;)

**Comment by sibelius** [comment]
I think now it is possible to share both

https://stackoverflow.com/questions/15496422/cant-share-both-image-and-text-through-whatsapp

**Comment by faxioman** [comment]
@sibelius this problem is iOS related. All works fine on Android.

**Comment by Davidcreador** [comment]
Yeah, what I did to resolve it was to remove the title from the options. Like @faxioman said. :)

**Comment by sibelius** [comment]
@Davidcreador could you share a snippet of share with base64 on whatsapp?

**Comment by sibelius** [comment]
@viniciusbo could you share your solution?

**Comment by sibelius** [comment]
I got it working here, Share.open works fine, but Share.shareSingle does not

**Comment by arjun9toppiks** [comment]
Anyone had this working with shareSingle?

**Comment by sagark1510** [comment]
Same issue, works on android but not on iOS. Any solution so far?

**Comment by melihberberolu** [comment]
Same issue, Anyone help me ? 
Message and url concated. So my base64 url looking string on iOS. Same options working on android without any problem.

**Comment by marf** [comment]
Same issue here. Is there a solution?

**Comment by firdausious** [comment]
Face the same issue.. doesn't work on iOS while sending message and image with base64

**Comment by jgcmarins** [comment]
@firdausious which version?
Could you provide a repo so we can reproduce?

**Comment by onurzorluer** [comment]
In IOS you must whitelist any URL schemes your App wants to query in Info.plist under the LSApplicationQueriesSchemes key (an array of strings).

Note that this mechanism only applies to canOpenURL and not openURL. You do not need to have a scheme listed in Info.plist to be able to open it with openURL. Hope that helps.

here is the code for your plist (add it at the end of the main dict node): `<key>LSApplicationQueriesSchemes</key> <array> <string>whatsapp</string> </array>`

**Comment by erick94isc** [comment]
Hi, @onurzorluer, that approche works for you? . Could you explain more about it? Because i have the same that you have and it's imposible to me send image + message on IOS in Android everything works fine.
